// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      //case TargetPlatform.iOS:
      //  return ios;
      //case TargetPlatform.macOS:
      //  return macos;
      //case TargetPlatform.windows:
      //  return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtT9tlWqqUkm7Dp5r6_JwtpzXdP_Wp_o',
    appId: '1:172591716619:web:69bb9566c82813e4a9aa0e',
    messagingSenderId: '172591716619',
    projectId: 'diagnosa-penyakit-kambing-app',
    authDomain: 'diagnosa-penyakit-kambing-app.firebaseapp.com',
    storageBucket: 'diagnosa-penyakit-kambing-app.firebasestorage.app',
    measurementId: 'G-1WF2DP942L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSYSVtuKNu4eKuMzxV1Rx2uuB-iCtwLw',
    appId: '1:172591716619:android:b305082f43ccf20aa9aa0e',
    messagingSenderId: '172591716619',
    projectId: 'diagnosa-penyakit-kambing-app',
    storageBucket: 'diagnosa-penyakit-kambing-app.firebasestorage.app',
  );

  //static const FirebaseOptions ios = FirebaseOptions(
  //  apiKey: 'AIzaSyBaszKkH43DZmFTqxyw4CCE0AaHQ9TJR6I',
  // appId: '1:172591716619:ios:49d7f32c2ae4a82da9aa0e',
  //  messagingSenderId: '172591716619',
  //  projectId: 'diagnosa-penyakit-kambing-app',
  //  storageBucket: 'diagnosa-penyakit-kambing-app.firebasestorage.app',
  //  iosClientId: '172591716619-913vf0ltvbcj6tda9jbgfea45bvuo3j3.apps.googleusercontent.com',
  //  iosBundleId: 'com.example.aplikasiDiagnosaPenyakitkambing',
  //);

  //static const FirebaseOptions macos = FirebaseOptions(
  //  apiKey: 'AIzaSyBaszKkH43DZmFTqxyw4CCE0AaHQ9TJR6I',
  // appId: '1:172591716619:ios:49d7f32c2ae4a82da9aa0e',
  //  messagingSenderId: '172591716619',
  //  projectId: 'diagnosa-penyakit-kambing-app',
  //  storageBucket: 'diagnosa-penyakit-kambing-app.firebasestorage.app',
  //  iosClientId: '172591716619-913vf0ltvbcj6tda9jbgfea45bvuo3j3.apps.googleusercontent.com',
  //  iosBundleId: 'com.example.aplikasiDiagnosaPenyakitkambing',
  //);

  //static const FirebaseOptions windows = FirebaseOptions(
  //  apiKey: 'AIzaSyCwtT9tlWqqUkm7Dp5r6_JwtpzXdP_Wp_o',
  //  appId: '1:172591716619:web:dcc4ab7d110136d2a9aa0e',
  //  messagingSenderId: '172591716619',
  //  projectId: 'diagnosa-penyakit-kambing-app',
  //  authDomain: 'diagnosa-penyakit-kambing-app.firebaseapp.com',
  //  storageBucket: 'diagnosa-penyakit-kambing-app.firebasestorage.app',
  //  measurementId: 'G-4LTTVYM5CX',
  //);
}
